exclude: migrations/.*\.py|Procfile|[aw]sgi\.py|node_modules|.git|\.polar|inputs/.*
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-json
  - id: check-toml
  - id: check-added-large-files
  - id: check-merge-conflict
  - id: detect-aws-credentials
  - id: detect-private-key
  - id: file-contents-sorter
    files: requirements.*\.in
  - id: mixed-line-ending
    args: [--fix, lf]
- repo: https://github.com/asottile/pyupgrade
  rev: v3.15.0
  hooks:
  - id: pyupgrade
    args: [--py310-plus]
- repo: https://github.com/asottile/yesqa
  rev: v1.5.0
  hooks:
  - id: yesqa
- repo: https://github.com/myint/docformatter
  rev: v1.7.5
  hooks:
  - id: docformatter
    args: [--in-place]
- repo: https://github.com/hadialqattan/pycln
  rev: v2.3.0
  hooks:
  - id: pycln
    args: [--config=pyproject.toml]
- repo: https://github.com/psf/black
  rev: 23.10.1
  hooks:
  - id: black
- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
  - id: isort
- repo: https://github.com/myint/autoflake
  rev: v2.2.1
  hooks:
  - id: autoflake
- repo: https://github.com/PyCQA/flake8
  rev: 6.1.0
  hooks:
  - id: flake8
    args: [--max-line-length=128, --extend-ignore=E203]
    exclude: .*migrations.*
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.11.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix]
- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.1.3
  hooks:
  - id: ruff
- repo: https://github.com/rtts/djhtml
  rev: 3.0.6
  hooks:
  - id: djhtml
  - id: djcss
    exclude: photosite/static/.*
  - id: djjs
    exclude: photosite/static/.*
