# Generated by Django 4.2.6 on 2023-10-07 18:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("product_url", models.CharField(max_length=255)),
                ("cover_photo_base_url", models.CharField(max_length=255)),
                ("cover_photo_media_item_id", models.CharField(max_length=255)),
                ("media_items_count", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Credentials",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("token", models.CharField(max_length=255)),
                ("expiry", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.CharField(max_length=255)),
                ("base_url", models.CharField(max_length=255)),
                ("filename", models.CharField(max_length=255)),
                ("mime_type", models.CharField(max_length=255)),
                ("product_url", models.CharField(max_length=255)),
                ("media_metadata", models.CharField(max_length=255)),
            ],
        ),
    ]
