# Generated by Django 4.2.6 on 2023-10-08 18:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("googlephotos", "0002_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="expires_at",
            field=models.DateTimeField(),
        ),
    ]
