# Generated by Django 4.2.6 on 2023-10-08 19:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("googlephotos", "0003_alter_token_expires_at"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Credentials",
        ),
    ]
