# Generated by Django 4.2.6 on 2023-10-14 09:10

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("googlephotos", "0007_photo_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlbumPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("intro", wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.RemoveField(
            model_name="photo",
            name="image",
        ),
        migrations.AddField(
            model_name="photo",
            name="photo",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to="wagtailimages.image"),
        ),
    ]
