# Generated by Django 4.2.6 on 2023-10-14 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("googlephotos", "0008_albumpage_remove_photo_image_photo_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="photo",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="wagtailimages.image"),
        ),
    ]
