# Generated by Django 4.2.6 on 2023-10-15 07:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("googlephotos", "0009_alter_photo_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="show",
            field=models.BooleanField(default=True),
        ),
    ]
