# Generated by Django 4.2.6 on 2023-10-16 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("googlephotos", "0010_photo_show"),
    ]

    operations = [
        migrations.AddField(
            model_name="albumpage",
            name="album",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="googlephotos.album"
            ),
        ),
    ]
