# Generated by Django 4.2.6 on 2023-10-21 08:51

import datetime
from django.db import migrations, models
from django.utils import timezone
from django.db.utils import IntegrityError
from datetime import datetime
from django.utils.timezone import make_aware, now

import json
from icecream import ic

def set_created(apps, schema_editor):
    photos = apps.get_model('googlephotos', 'Photo')
    for photo in photos.objects.all().iterator():
        metadata = json.loads(photo.media_metadata.replace("'", '"'))
        try:
            created = datetime.strptime(metadata["creationTime"], "%Y-%m-%dT%H:%M:%SZ")
            photo.creation_time = make_aware(created)
        except KeyError:
            photo.creation_time = timezone.now()
        photo.save()
    ic("done")

def reverse_func(apps, schema_editor):
    pass  # code for reverting migration, if any


class Migration(migrations.Migration):
    dependencies = [
        ("googlephotos", "0011_albumpage_album"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="creation_time",
            field=models.DateTimeField(default=now),
            preserve_default=False,
        ),
        migrations.RunPython(set_created, reverse_func),
    ]
