# Generated by Django 4.2.6 on 2023-10-27 18:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("googlephotos", "0012_photo_creationtime"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="photo",
            options={"ordering": ["-creation_time"]},
        ),
    ]
