# Generated by Django 4.2.6 on 2023-10-27 19:01

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_homepage_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="content",
            field=wagtail.fields.StreamField(
                [("Paragraph", wagtail.blocks.RichTextBlock()), ("AlbumList", wagtail.blocks.StructBlock([]))],
                blank=True,
                use_json_field=True,
            ),
        ),
    ]
